# Build stage
FROM node:18 AS build

WORKDIR /app
COPY . .
RUN npm install
RUN npm run build

# Run stage
FROM nginx:alpine

COPY --from=build /app/build /usr/share/nginx/html
COPY nginx/default.conf /etc/nginx/conf.d/default.conf

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]